permalink: "/:title"

# Setup
title:               'Gaurav Agrawal'
tagline:             'Just Another Blog'
description: >
        An insight into some of my ongoing development works and open source engagement .....
url:                https://gaurav1999.github.io/
baseurl:             ''
paginate: 4    
twitter_username: GauravGnome
github_username: gaurav1999
githubrepo: https://gaurav1999.github.io/
google_analytics: UA-134373511-3
markdown: kramdown
paginate_path: "recent_blogs/page:num/"
inter_post_navigation: true

author:
  name: Gaurav Agrawal
  url: https://twitter.com/GauravGnome
  email: agrawalgaurav1999@gmail.com

# Custom vars

gems: [jekyll-paginate]
social:
  - name: Twitter
    icon: twitter
    username: GauravGnome
    url: https://twitter.com/GauravGnome
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: gaurav1999
    url: https://github.com/gaurav1999
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Gaurav Agrawal
    url: linkedin.com/in/gaurav-agrawal-176a7616a
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    #fb_image: "/assets/nr-logo.jpg"
    #fb_image_width: 612
    #fb_image_height: 605
    #fb_image_type: "image/jpg"

    #twitter_image: "/assets/nr-logo.jpg"

    os_repo:"https://github.com/gaurav1999.github.io"
    os_rcs_type:"git"
    os_src:"git@github.com:gaurav1999.github.io.git"1
