permalink: "/:title"

# Setup
title:               Antares'
tagline:             'Tech Voyage'
description: >
        An insight into some of my technical quests .....
url:                https://aakp10.github.io/
baseurl:             ''
paginate: 4    
twitter_username: antares_9119
github_username: aakp10
githubrepo: https://aakp10.github.io/
google_analytics: UA-111511851-1
markdown: kramdown
paginate_path: "recent_blogs/page:num/"
inter_post_navigation: true

author:
  name: Karuna Grewal
  url: https://twitter.com/antares_9119
  email: karunagrewal98@gmail.com

# Custom vars

gems: [jekyll-paginate]
social:
  - name: Twitter
    icon: twitter
    username: antares_9119
    url: https://twitter.com/antares_9119
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: aakp10
    url: https://github.com/aakp10
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Karuna Grewal
    url: linkedin.com/in/karuna-grewal-909074141
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    #fb_image: "/assets/nr-logo.jpg"
    #fb_image_width: 612
    #fb_image_height: 605
    #fb_image_type: "image/jpg"

    #twitter_image: "/assets/nr-logo.jpg"

    os_repo:"https://github.com/aakp10.github.io"
    os_rcs_type:"git"
    os_src:"git@github.com:aakp10.github.io.git"1
